/* auto-generated by NAPI-RS */
/* eslint-disable */

export class CodeExplorer {
  constructor(rawCode: string)
  findImports(): Array<ImportResults>
}

export interface ImportResults {
  ids: Array<string>
  source: string
}

