/* auto-generated by NAPI-RS */
/* eslint-disable */

export class CodeExplorer {
  constructor(rawCode: string)
  findImports(): Array<ImportResults>
}

export interface ImportBinding {
  local: string
  imported: string
  isType: boolean
}

export interface ImportResults {
  bindings: Array<ImportBinding>
  source: string
}

