/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function findImports(code: string): Array<ImportResults>
export class ImportResults {
  ids: Array<string>
  source: string
}
